services:
  web:
    build: .
    container_name: offlinebox
    ports:
      - "8888:80" # Host port : Container port
    volumes:
      - ./sourceFiles/.:/var/www/html
      - ${BACKUP_PATH}:/var/backups/local
    command: sh -c "cron && tail -f /var/log/cron.log & apache2-foreground"
