version: '3.8'

services:
  web:
    build: .
    container_name: offlinebox
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sourceFiles/.:/var/www/html
      - ./backups/.:/var/backups/local
    command: sh -c "cron && tail -f /var/log/cron.log & apache2-foreground"
